language: php

php:
    - 5.3
    - 5.4
    - 5.5

before_script: composer install --dev

script:
    - bin/atoum -d Tests/Units

notifications:
    email:
        recipients:
            - ci@verylastroom.com
        on_success: change
        on_failure: change
